\title{Task-Oriented Guidance for Information Visualization Recommendation}

% for anonymous conference submission please enter your SUBMISSION ID
% instead of the author's name (and leave the affiliation blank) !!
\author[Marcin Konefal]
       {Marcin Konefal\\
	Matricual number: 11834279\\
	188.943 - Project in Visual Computing\\
	Praktikum\\
	\\
	Supervision:\\
	Dipl.-Ing. Dr. Harald Piringer$^{1}$\\
	Assistance:\\
	Univ.-Prof. Mag. Dr. Silvia Miksch$^{2}$
        \\\\
% For Computer Graphics Forum: Please use the abbreviation of your first name.
	 $^1$VRVis Zentrum für Virtual Reality und Visualisierung Forschungs-GmbH, Austria\\
         $^2$Institute of Visual Computing and Human-Centered Technology, TU Wien, Austria
       }

\begin{document}

\maketitle
\section{Introduction}


%-------------------------------------------------------------------------
\section{Problem Description}


%-------------------------------------------------------------------------
\section{Expected Results}


%-------------------------------------------------------------------------
\section{Method}


%-------------------------------------------------------------------------
\section{References}


%-------------------------------------------------------------------------

%\bibliographystyle{eg-alpha}
\bibliographystyle{eg-alpha-doi}

\bibliography{egbibsample}

%-------------------------------------------------------------------------

\end{document}
